apiVersion: aws.pandurang.com/v1
kind: PandurangAWSEC2
metadata:
  labels:
    app.kubernetes.io/name: pandurangawsec2
    app.kubernetes.io/instance: pandurangawsec2-sample
    app.kubernetes.io/part-of: vmstate-operator-pk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vmstate-operator-pk
  name: pandurangawsec2-sample
spec:
  # TODO(user): Add fields here
