# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/azure.pandurang.com_pandurangazureavms.yaml
- bases/gcp.pandurang.com_panduranggcpgces.yaml
- bases/aws.pandurang.com_pandurangawsec2s.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_pandurangazureavms.yaml
#- patches/webhook_in_panduranggcpgces.yaml
#- patches/webhook_in_pandurangawsec2s.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_pandurangazureavms.yaml
#- patches/cainjection_in_panduranggcpgces.yaml
#- patches/cainjection_in_pandurangawsec2s.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
